#!/bin/sh

# -------------------------------------------------------
# A shell script that sets the brightness level
# Written by: Thomas Venries
# Last updated on: 2016/7/11
# -------------------------------------------------------

#set -e

usage() {
	echo "Usage: lightmano [OPTION]..."
	echo -e "Option values are positive integers.\n"

	echo "Operations:"
	echo -e "-h:\tPrint this help and exits\n"

	echo "Threshold (can be used in conjuntion):"
	echo -e "-m:\tSet the minimum brightness"
	echo -e "-M:\tSet the maximum brightness"
	echo -e "-c:\tSet the controller\n"

	echo "Controller (can not be use in conjunction):"
	echo -e "-a:\tAdd value"
	echo -e "-s:\tSubtract value"
	echo -e "-S:\tSet the brightness\n"

	echo -e "No option (read values):  <controller_path>: min;current;max\n"
}

no_conjunction_with() {
	while [ $# -ne 0 ]; do
		[ "$1" = true ] && break || shift
	done

	if [ $# -eq 0 ]; then
		return 1
	fi

	echo "Operation arguments can not be used in conjunction."
	return 0
}

is_positive_integer() {
	[[ "$1" =~ ^[0-9]+ ]] && return 1 || return 0
}

check_controller() {
	if ! [ "$#" -eq 1 ]; then return 0; fi

	if ! [ -f "$1/max_brightness" ] ||
		! [ -f "$1/brightness" ] ||
		! [ -r "$1/max_brightness" ] ||
		! [ -r "$1/brightness" ] ; then
		#! [ -w "${i}/brightness" ] ; then
	return 0
	fi
	return 1
}

main() {
	mFlag=false
	MFlag=false
	cFlag=false
	aFlag=false
	sFlag=false
	SFlag=false

	OPTIND=1
	while getopts "hm:M:c:a:s:S:" opt; do
		case $opt in
			h) usage && exit 0;;
			m)
				is_positive_integer "$OPTARG"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				mFlag=true
				mArg=$OPTARG
				;;
			M)
				is_positive_integer "$OPTARG"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				MFlag=true
				MArg=$OPTARG
				;;
			c)
				check_controller "$OPTARG"
				if [ "$?" -eq 0 ]; then
					echo "Controller '$OPTARG' not found."
					exit 1
				fi
				cFlag=true
				cArg=$OPTARG
				;;
			a)
				no_conjunction_with "$sFlag" "$SFlag"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				is_positive_integer "$OPTARG"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				aFlag=true
				valArg=$OPTARG
				;;
			s)
				no_conjunction_with "$aFlag" "$SFlag"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				is_positive_integer "$OPTARG"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				sFlag=true
				valArg=$OPTARG
				;;
			S)
				no_conjunction_with "$aFlag" "$sFlag"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				is_positive_integer "$OPTARG"
				if [ "$?" == 0 ]; then usage; exit 2; fi
				SFlag=true
				valArg=$OPTARG
				;;
			\?) exit 2 ;;
			:) exit 2 ;;
		esac
	done

	best_controller=
	best_max=0

	if [ "$cFlag" = true ] ; then
		best_controller=$cArg
		best_max=`cat $best_controller/max_brightness`
	else
		# Try to find the best-max-value controller
		for i in `echo /sys/class/backlight/*` ; do
			check_controller ${i}
			[ "$?" -eq 0 ] && continue
			max=`cat ${i}/max_brightness`
			if (( "$best_max" < "$max" )) ; then
				best_max=$max
				best_controller=${i}
			fi
		done

		if [ -z "$best_controller" ] ; then
			echo "Controller not found."
			exit 1
		fi
	fi

	own_min=0
	own_max=$(( best_max-1 ))
	file="$best_controller/brightness"
	brightness=$(cat $file)

	if [ "$#" -eq 0 ]; then
		echo "$best_controller: $own_min;$brightness;$own_max"
		exit 0
	fi

	# No set option
	if [ "$aFlag" = false ] && [ "$sFlag" = false ] && [ "$SFlag" = false ]
	then
		usage; exit 0
	fi

	[ "$mFlag" = true ] && own_min=$mArg
	[ "$MFlag" = true ] && own_max=$MArg

	if [ "$aFlag" = true ]; then
		value=$(( brightness+valArg ))
		if (( $brightness == 0 )) ; then
			value=$(( own_min+valArg ))
		elif (( "$value" > "$own_max" )) ; then
			value=$own_max
		fi
		echo $value | sudo /usr/bin/tee $file
	fi

	if [ "$sFlag" = true ]; then
		value=$(( brightness-valArg ))
		(( $value <= $own_min )) && value=0
		echo $value | sudo /usr/bin/tee $file
	fi

	if [ "$SFlag" = true ]; then
		value=$valArg
		if (( $value > $own_max )) ; then
			value=$own_max
		elif (( $value < $own_min )) ; then
			value=0
		fi
		echo $value | sudo /usr/bin/tee $file
	fi

	shift "$((OPTIND-1))"
}

main "$@"
