#!/bin/bash

usage() {
	echo -e "Usage: lux [OPTION]...
Brightness's option values are positive integers.
For percent mode: add '%' after value.

Information:
  -h:\t\t\tPrints this help and exits
  -v:\t\t\tPrints version info and exists
  (none):\t\tPrints controller's name and brightness info
  \t\t\t\"{controller} {min;value;max}\"

Brightness threshold options (can be used in conjunction):
  -m:\t\t\tSet the brightness min
  -M:\t\t\tSet the brightness max

Brightness value options (can not be use in conjunction):
  -a:\t\t\tAdd value
  -s:\t\t\tSubtract value
  -S:\t\t\tSet the brightness value

Controller options (can be used with brightness options):
  -c {controller}:\tSet the controller (/sys/class/backlight/{controller})\n"
}

version() {
	echo -e "Lux 0.5 (beta)
Copyright (C) 2016 Thomas Venriès.
License GPLv3+: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.\n"
}


no_conjunction_with() {
	while [ $# -ne 0 ]; do
		[ "$1" = true ] && break || shift
	done

	if [ $# -eq 0 ]; then
		return 1
	fi

	echo "Operation arguments can not be used in conjunction."
	return 0
}

is_positive_integer() {
	[[ "$1" =~ ^[0-9]+ ]] && return 1 || return 0
}

is_percentage() {
	local out=`echo $1 | grep -e "%$"`
	if [ -z "$out" ]; then
		return 0
	fi
	return 1
}

check_controller() {
	[ ! -d "${1}" ] && return 1 || return 0
}

main() {
	local PERCENT_MODE=false

	local mFlag=false
	local MFlag=false
	local cFlag=false
	local aFlag=false
	local sFlag=false
	local SFlag=false

	OPTIND=1
	while getopts "hvm:M:c:a:s:S:" opt; do
		case $opt in
			h) usage && exit 0;;
			v) version && exit 0;;
			m)
				is_positive_integer "$OPTARG"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				mFlag=true
				mArg=$OPTARG
				;;
			M)
				is_positive_integer "$OPTARG"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				MFlag=true
				MArg=$OPTARG
				;;
			c)
				controller_path="/sys/class/backlight/$OPTARG"
				check_controller $controller_path
				if [ "$?" -eq 1 ]; then
					echo "$controller_path: controller not found."
					exit 0
				fi
				cFlag=true
				cArg=$controller_path
				;;
			a)
				no_conjunction_with "$sFlag" "$SFlag"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				is_percentage "$OPTARG"
				if [ "$?" -eq 1 ]; then
					PERCENT_MODE=true
					OPTARG=`echo $OPTARG | cut -d % -f 1`
				fi
				is_positive_integer "$OPTARG"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				aFlag=true
				valArg=$OPTARG
				;;
			s)
				no_conjunction_with "$aFlag" "$SFlag"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				is_percentage "$OPTARG"
				if [ "$?" -eq 1 ]; then
					PERCENT_MODE=true
					OPTARG=`echo $OPTARG | cut -d % -f 1`
				fi
				is_positive_integer "$OPTARG"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				sFlag=true
				valArg=$OPTARG
				;;
			S)
				no_conjunction_with "$aFlag" "$sFlag"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				is_percentage "$OPTARG"
				if [ "$?" -eq 1 ]; then
					PERCENT_MODE=true
					OPTARG=`echo $OPTARG | cut -d % -f 1`
				fi
				is_positive_integer "$OPTARG"
				if [ "$?" -eq 0 ]; then usage; exit 2; fi
				SFlag=true
				valArg=$OPTARG
				;;
			\?) exit 2 ;;
			:) exit 2 ;;
		esac
	done

	local best_controller=""
	local best_max=-1

	if [ "$cFlag" = true ] ; then
		best_controller=$cArg
		best_max=`cat $best_controller/max_brightness`
	else
		# Try to find the best-max-value controller
		for i in `echo /sys/class/backlight/*` ; do
			check_controller ${i}
			[ "$?" -ne 0 ] && continue
			max=`cat ${i}/max_brightness`
			if (( "$best_max" < "$max" )) ; then
				best_max=$max
				best_controller=${i}
			fi
		done

		[ "${i: -1}" == "*"  ] && echo "There is no controller" && exit 0
	fi

	local own_min=0
	local own_max=$(( best_max-1 ))
	local file="$best_controller/brightness"
	local brightness=$(cat $file)

	if [ "$#" -eq 0 ]; then
		echo "$best_controller $own_min;$brightness;$own_max"
		exit 0
	fi

	# No set option
	if [ "$aFlag" = false ] && [ "$sFlag" = false ] && [ "$SFlag" = false ]
	then
		usage; exit 0
	fi

	[ "$mFlag" = true ] && own_min=$mArg
	[ "$MFlag" = true ] && own_max=$MArg

	if [ "$aFlag" = true ]; then
		if [ "$PERCENT_MODE" = true ]; then
			valArg=$(( (own_max - own_min) * valArg / 100 ))
		fi
		value=$(( brightness+valArg ))
		if (( $brightness == 0 )) ; then
			value=$(( own_min+valArg ))
		elif (( "$value" > "$own_max" )) ; then
			value=$own_max
		fi
		echo $value | /usr/bin/tee $file
	fi

	if [ "$sFlag" = true ]; then
		if [ "$PERCENT_MODE" = true ]; then
			valArg=$(( (own_max - own_min) * valArg / 100 ))
		fi
		value=$(( brightness-valArg ))
		(( $value <= $own_min )) && value=0
		echo $value | /usr/bin/tee $file
	fi

	if [ "$SFlag" = true ]; then
		if [ "$PERCENT_MODE" = true ]; then
			valArg=$(( own_min + (own_max - own_min) * valArg / 100 ))
		fi
		value=$valArg
		if (( $value > $own_max )) ; then
			value=$own_max
		elif (( $value < $own_min )) ; then
			value=0
		fi
		echo $value | /usr/bin/tee $file
	fi

	shift "$((OPTIND-1))"
}

main "$@"
